### PR TITLE
fix(index): use customer namespace

### LINKED ISSUE #52: invoke word2md gdocs2md on the same namespace as the action runs
**Description**
the word2md and gdocs2md are invoked on the `helix` namespace, which is sub-optimal as they activation should be on the customers namespace:

https://github.com/adobe/helix-content-proxy/blob/b5b9963041164bce79855d9726bae2c8ac32c5dc/src/onedrive.js#L35

### suggestion

the the same namespace as the content-proxy action is using.

i.e. use `process.env.__OW_NAMESPACE` instead.

### PR DESCRIPTION
**Pull request by trieloff**
fixes #52

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -47,6 +47,7 @@ async function main({
   AZURE_WORD2MD_CLIENT_ID, AZURE_WORD2MD_CLIENT_SECRET,
   AZURE_HELIX_USER, AZURE_HELIX_PASSWORD,
   __ow_headers: originalHeaders = {}, __ow_logger: log,
+  __ow_namespace: namespace = 'helix',
```
Comment (tripodsan) [inline src/index.js:50]: are you sure this is present? usually it's the `process.env.__OW_NAMESPACE`:

```
$ curl -sD- https://adobeioruntime.net/api/v1/web/tripod/default/dump
HTTP/1.1 200 OK
....

{
  "__ow_method": "get",
  "__ow_path": ""
}
```
