### PR TITLE
fix: force http1 when invoking other runtime actions

### LINKED ISSUE #196: ERR_HTTP2_INVALID_SESSION when proxying against other runtime actions
**Description**
during a recent outage, non of the invocations to content proxy was able to deliver content, if it was fetching it from another runtime action. the error was:

```
Unhandled error Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed at ClientHttp2Session.request (internal/http2/core.js:1558:13)
```

The proxy requests to github still worked.

During the same time, Adobe I/O Runtime changed some routing of their traffic. 

---

After forcing HTTP1 and redeploying the action, everything worked again normally. Interestingly, deploying another version with http2 still enabled also worked. also, requesting older versions e.g. 2.0.7 also works now.

also, before the deployment with http2 disabled, I never tried to invoke the content proxy directly, the errors were only observed in coralogix. so it might well be, that it worked before invoking the action directly with curl (and not via fastly)

also, looking at the activations, there were many cold starts, which I assume rules out any problems in caches inside the nodejs process. My wildest guess is, that some network information (dns, route, cert) somehow changed but wasn't updated in the cache of the container environment and caused problems establishing the http2 session....

---

Unfortunately, it's not possible to reproduce the issue. there was a similar behaviour in helix-static and the typekit fonts: https://github.com/adobe/helix-static/issues/351

/cc @stefan-guggisberg @tysonnorris

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
The upcoming/new I/O Runtime environment is Azure-based and supports HTTP/2. This might lead to issues with long-lived HTTP/2 sessions.

fix #196

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues
#196 

Thanks for contributing!

### CODE REVIEW

**Review by trieloff — APPROVED** [review]

File: src/utils.js [hunk 1]
```diff
@@ -14,12 +14,9 @@ const { URL } = require('url');
 const fetchAPI = require('@adobe/helix-fetch');
 
 function createFetchContext() {
-  /* istanbul ignore next */
-  if (process.env.HELIX_FETCH_FORCE_HTTP1) {
```
Comment (tripodsan) [inline src/utils.js:18]: I would keep the `if` and just set `process.env.HELIX_FETCH_FORCE_HTTP1 = 'true'`

**Review by tripodsan — CHANGES_REQUESTED** [review]
don't remove `if`

**Review by tripodsan — APPROVED** [review]
